# Generated by Django 2.0.3 on 2018-03-08 11:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=150)),
                ('lastname', models.CharField(max_length=150)),
                ('created_at', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.AlterField(
            model_name='article',
            name='created_at',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.ForeignKey(default=0, on_delete=None, to='articles.Author'),
            preserve_default=False,
        ),
    ]
